### ISSUE TITLE
Example fails with message "SendRoutine: use of closed network connection"

### ISSUE THREAD

**Issue by pixelbender** [sdidyk/telegram#1]
> telegram auth 7985xxxxxxx
> Fails with single line "SendRoutine: use of closed network connection"
> ~/.telegram_go - contains 304 bytes

**Comment by sdidyk** [comment]
confirmed :(

**Comment by sdidyk** [comment]
Telegram server breaks the connection immediately after sending __MIGRATE__ errors. So I'll fix it in a day or two.

**Comment by sdidyk** [comment]
@pixelbender, please check it now.

**Comment by pixelbender** [comment]
@sdidyk same issue (

**Comment by aglossa** [comment]
Same result with a French number 33XXXXXXXXX.
NB : compiled with go1.4.2 on linux

How can I help to debug this issue ?
NB : if this is a firewall/iptables issue, a solution would be some documentation.

**Comment by mz1988** [comment]
you don't have plan to fix this ?

**Comment by sdidyk** [comment]
@mz1988 @aglossa 
1. i've fixed this bug with the valid reconnection
2. i noticed that telegram servers do not send 303 code now
