### ISSUE TITLE
Fix Vector encoding

### ISSUE THREAD

**Issue by andrebq** [sdidyk/telegram#10]
At: https://github.com/sdidyk/mtproto/blob/master/tl_encode.go#L121

The "append" operations inserts 512 bytes to the current buffer, when the correct thing would be including only 8 bytes (vectory type identification and vector length).

I founded the error while trying to call TL_contacts_importContacts.

**Comment by sdidyk** [comment]
@andrebq, thank you very much!
It's a dumbest typo so far :(
