### ISSUE TITLE
createGeoChat

### ISSUE THREAD

**Issue by marco-fabbri** [sdidyk/telegram#8]
Hey, you're doing an awesome job!

I'm trying to use `TL_geochats_createGeoChat` but I'm getting a weird error, in my opinion the answer schema is still disabled but I'm asking your opinion to confirm my thesis.

This is what I get:

```
leaf:telegram dunric$ ./telegram creategeochat
RPC: mtproto.TL_rpc_error{error_code:400, error_message:"INPUT_METHOD_INVALID"}
leaf:telegram dunric$
```

This is my piece of code:

```
func (m *MTProto) CreateGeoChat() error {
    var inputGeoPoint = TL_inputGeoPoint{44.4931088, 11.3377388}

    resp := make(chan TL, 1)
    m.queueSend <- packetToSend{
        TL_geochats_createGeoChat{
            "My Venue",
            inputGeoPoint,
            "My address",
            "My foursquare URL",
        },
        resp,
    }
    x := <-resp
    _, ok := x.(TL_geochats_statedMessage)
    if !ok {
        return fmt.Errorf("RPC: %#v", x)
    }

    return nil
}
```

Any idea?

**Comment by sdidyk** [comment]
1. check seriazliation of type double :)
2. may be telegram guys blocks those geochats in layer 23? i see "Type schema is not available in the selected layer" in some methods/objects like https://core.telegram.org/type/geochats.StatedMessage

**Comment by marco-fabbri** [comment]
1. i tried using `getRecents` (https://core.telegram.org/method/geochats.getRecents) and i'm having the same error, that points to your 2
2. i had the same feeling reading that period, that's why i contacted telegram support but i didn't receive anything useful

my point 3 is: we're actually authenticating with our gsm number, what about using API keys? is it the same?

**Comment by marco-fabbri** [comment]
Forget point 3 😛 

I tried to create e normal chat (group) and i'm getting erorr 400 again. Do you get what i am doing wrong?

My error:

```
leaf:telegram dunric$ ./telegram createchat
RPC: mtproto.TL_rpc_error{error_code:400, error_message:"INPUT_CONSTRUCTOR_INVALID"}
leaf:telegram dunric$

```

My piece of code:

```
func (m *MTProto) CreateChat() error {
    resp := make(chan TL, 1)
    m.queueSend <- packetToSend{
        TL_messages_createChat{
            []TL{TL_inputUserContact{2921643}},
            "My Chat",
        },
        resp,
    }
    x := <-resp
    _, ok := x.(TL_messages_statedMessage)
    if !ok {
        return fmt.Errorf("RPC: %#v", x)
    }

    return nil
}
```

**Comment by sdidyk** [comment]
I've got same result :( I think layer 23 is kinda deprecated for the TG servers, Durov has chosen offical clients for TG and the quality support for public API is no more needed.

**Comment by marco-fabbri** [comment]
I had this answer from BotSupport:

> Regarding your question, I want to let you know that geochat are just part of the old api layers, they are not any more present, so I don't recomend you to use them.

What do you think about the `TL_messages_createChat` instead?

**Comment by sdidyk** [comment]
With fixed "Vector bug" it's working now.
For TL_messages_createChat try
```
        TL_messages_createChat{
            []TL{TL_inputUserSelf{}, TL_inputUserContact{132597}},
            "My Chat",
        },
```
Second peer must be your contact or you should get USERS_TOO_FEW error response.

**Comment by ngopher** [comment]
Hi @sdidyk 
I am using your mtproto code for developing an sapmle app for only add contact and send message.
I had wrote all methods successfully, but I can not implement method for add contact!
there is the method: please help me to complete it. I have error : INPUT_CONSTRUCTOR_INVALID , too.
/////////////////////////////////
func (m *MTProto) Contacts_ImportContacts(in []TL) TL_contacts_importedContacts {
	resp := make(chan TL, 1)
	m.queueSend <- packetToSend{
		TL_contacts_importContacts{in, TL_boolFalse{}}, resp}
	x := <-resp
	switch r := x.(type) {
	case TL_contacts_importedContacts:
		return r
	default:
		log.Println(x)
	}
	return TL_contacts_importedContacts{}
}
///////////////////////////////////////////////
and this is call of method:
func importContact(c *gin.Context) {
	m, err := mtproto.NewMTProto(os.Getenv("HOME") + "/.telegram_go")
	if err != nil {
		fmt.Printf("Create failed: %s\n", err)
		os.Exit(2)
	}
	_ = m.Connect()
	var NewContact mtproto.TL_inputPhoneContact
	NewContact.Last_name = ""
	NewContact.First_name = ""
	NewContact.Phone = "0989212049236"
	NewContacts := []mtproto.TL{NewContact}
	x := m.Contacts_ImportContacts(NewContacts)
	c.JSON(200, gin.H{"status": x})

}
